### ISSUE TITLE
Elección del lenguaje de programación

### ISSUE THREAD

**Issue by pablotl0** [evaanngiil/WishfulGiving#11]
Buenas @evaanngiil , debemos ponernos de acuerdo sobre qué lenguaje de programación sería el más adecuado para este proyecto  ¿Qué lenguaje consideras mas viable?

**Comment by evaanngiil** [comment]
Buenas @pablotl0, considerando la estructura de datos de datos de mi aplicación y una programación orientada a objetos, creo que lo más seguro sería algún lenguaje relacionado con Java (como Java puro). O por contra, Python por su simpleza y eficiencia. Quedo a tu elección.

**Comment by pablotl0** [comment]
Hola @evaanngiil, Java es una elección sólida para este caso. Ofrece herramientas robustas para manejar datos complejos, una estructura bien definida y un ecosistema que soporta el desarrollo orientado a objetos.

**Comment by evaanngiil** [comment]
Me parece una opción perfecta para este ejemplo. 
Comentar que he añadido en af99e962527191bd1207ad3dff838abd9ca6c872 el archivo de user-journeys que habia borrado sin darme cuenta.
